### ISSUE TITLE
Users

### ISSUE THREAD

**Issue by yohagos** [yohagos/midgard#1]
Entity fields and methods:

- [x] Entity and Table Annotations
- [x] ID
- [x] Firstname
- [x] Lastname
- [x] Email
- [x] Password
- [x] Timestamp (creation timestamo)
- [x] Getters and Setters
- [x] toString()

Repository:

- [x] Repository Annotation
- [x] UserRepository extending JpaRepository
- [ ] Custom methods (e.g. findByEmail)

Service:

- [x] Service Annotations
- [x] UserRepository field
- [x] Initialized through Contructor
- [x] Methods needed

Conntroller:

- [x] RestController and RequestMapping Annotations
- [x] UserService field
- [x] UserService initialized through Contructor
- [x] API's
