### ISSUE TITLE
Tickets

### ISSUE THREAD

**Issue by yohagos** [yohagos/midgard#2]
Entity fields and methods:

- [x] Entity and Table Annotations
- [x] ID
- [x] Owner
- [x] IncludeUsers
- [x] Content
- [x] Timestamp (creation timestamo)
- [x] Timestamp (closed timestamp)
- [x] Getters and Setters
- [x] toString()

Repository:

- [x] Repository Annotation
- [x] TicketRepository extending JpaRepository
- [x] Custom methods (e.g. findByName or categories)

Service:

- [x] Service Annotations
- [x] TicketRepository field
- [x] Initialized through Contructor
- [x] Methods needed

Conntroller:

- [x] RestController and RequestMapping Annotations
- [x] TicketService field
- [x] TicketService initialized through Contructor
- [x] API's
