### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by yohagos** [yohagos/midgard#4]
Entity fields and methods:

- [x] Entity and Table Annotations
- [x] ID
- [x] TicketID
- [x] User
- [x] Content
- [x] Timestamp (creation timestamo)
- [x] Getters and Setters
- [x] toString()

Repository:

- [x] Repository Annotation
- [x] CommentRepository extending JpaRepository
- [x] Custom methods (e.g. findByUser)

Service:

- [x] Service Annotations
- [x] CommentRepository field
- [x] Initialized through Contructor
- [x] Methods needed

Conntroller:

- [x] RestController and RequestMapping Annotations
- [x] CommentService field
- [x] CommentService initialized through Contructor
- [x] API's
